---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: prd
spec:
  encryptedData:
    DB_PASSWORD: AgAkY8wQv0cce/RKxAxvplTHVl+mChNi4kMjx0yIMPMef/edzGtB1AxJx7oYiRqF0DrOTW0bLeuLWDWxdHELOd/asTCn3UEF3qNWJLT3WIXz2Y8HIZNH7yZJJeOVFGH+SuKlvcsiqe+iZzroPWEFqP5eeo3edsVk6+aqKFUT5DWttP5afPBwVZ/DPC+Tuanh6O4n8q9e2yM8wQpjeopxcqFhvv6yrqKowxjwYAMy4lWcBVgv/hPBaIpbbM7Dzm5GOXaWnwVoBwfVoZvUATPTiNl1LNrDqCORbqSzndR18DK9JDfEcwbvTqEvagvoR/+UbAus8SmFn6CPymiYmSMmuPYyC/9PnCfbmbQx9So5lazih8JTzbxh89AaPpt9Ov8AaXZtlS/Eo2J9D5GyzWEdLdXnfe8YgimKvsOQ+rAGxFRWN8YCk4eENjeU5iRSlqw2UhRR1LAGNV3qWZnI4ltNGMr/13yfWdkR9nHWm00f3tOzaMAvg/SqNzSGfk235IEwv+MmuHPcQFVeiB8meD5/29pzwKvY30NlYJMtdJlR68YvdTPiV6x9mUwrfhSfpkg+TW6OeLMGK/7nECMlqZeYOGa6nLxvHf6iFwN2aijqYtCTNuZCEg3MGt+rrpV5cxyzWly/in5FxdVGONA5sKdna8Q29Mx9gYGNFxy62XWUCt/XLaE5ORt48Hc+y9ok2EX6Qp1Dr16T0XN1uV7hroRPwn/VuhW5QsOdQg==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: prd
    type: Opaque
