---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  encryptedData:
    DB_PASSWORD: AgA/iArHwRlEUyvRayegD3gbBtsfttZaBRXxXeKREUY5EgAUzfwT1IcmckWFbuOjKy25sLy7IubVhv9rOKjlYTxJeEwsnrbsdExsBo2Q2ECPcCuJbPQ2R6P16ajWCHVHx+5BulNxFCblt4YSqlAzFPMIwZ3dZUA3xRezG8E/huaLbpKKwjxUFg+uDz1HrXJ9+PdFEu8KoQOGV+f7LQz5mlNEwfmI0XPFwVOjfybGqXmodqHo3+3cebM8bI6bXh0HoWal07O34yPAB2jafDSFstCSLN/0/eEq+1aOvHfZ0Woy+6CGaIN29tgG05E42tHMvyz0Z+DGnbiv3HC6VWutJKjuWj6zNJOsHJl0cpjaddszSkoAPU/Cp+kojjMTNvJkwQkk4HJDfipP/SUgHKlzpyyL83AN8EKMPdk0pvu+kV5Ab+hetAnPgzJeiygdlkreJNYwjT5ExnX66BFpzYueGMSRVAYnXRqYf+ln29d520C71wWr1ZEojFvGibuS7AastDhYEYBUhtL81sFBf6TBNglWlWnAnzAZgld2tpoMX6Bsmh9s6YKRLvcmz3Cit4UHTSmucKID1a4B2aW2qELFeran0f9BD/11W/bfHV69+b3RdPFHgrl+q+ZGryZZo+hBOyWmMcuKiGCLqJzH1UDUCuFv7FwX0phggJbPMUfYQe85wCKKM4Nq+q8+Pul1a4DLi8/MgbjTQrQ=
  template:
    metadata:
      name: sealed-secrets
      namespace: argocd
    type: Opaque
