---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  encryptedData:
    DB_PASSWORD: AgANyIEOkB9s1ZzhAJRYqrHHIjMKVr9f8KzjnpSJVwm3YVFa3md38IdSxgzBeuk0ISn7r4g8D5fY0Or3UsqJWQLN7bpYF+1qO7iU1aeQI9D3rxtIaZPfgDFfM4kA6HSJrvjT9lJ+9yT9bFa6OgsqQi+TBgOnuscJ4j1qgRGUebaz3y2tpUlxR0hVr9KaQNZuAlGNX3CAhAlwVrBQOjtcs357gEJIO/5qj/EIHXXYeqqxmKYVehtpzvTuc6+0d42rCn3OeVm0sl5RNwApnSUJdOhgRil80UCQPJ9oQ8KMwHTlkX5lqgOom1f0lzdZECk5WFvG+QfFfIBh/FoJS5kbvebyn0ONNj6vosytaxy7ciIhNCfnfKhmdWt6n97lW48RUW2b4xsSBzm5FHQi5N7QzYmpv02RYxCNSwiMMBZR3BBt/d95vhjcNR1tdpOKRgablEtEKYRT+CSgFe23XJma+T8jssx7KYL5N3/QzIkIrMmY4FGq8ol/m/u78/gyFOCfgWE4GjSBENEWuWaC66MFr53rQ9nJyaSWOgUjT4ep15btJNamwBiDJr8SEvLxuawNxuRsT5V5LFJYYOxBJMx43H/eOnsuJTZhDWNOhYcBKFa0a2ieDFisfoPGeBItRhlPPepH+IJoj7Gb0jylZMUt1Km67ygeAqF88TJH2JJbyeNoZDEu1KIzmfxFJy1oY4wxyKq3gchj7A==
  template:
    metadata:
      name: sealed-secrets
      namespace: argocd
    type: Opaque
