---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  encryptedData:
    DB_PASSWORD: AgB0nBhIANcCuropoU1EG/ysvP+kMyUTyVqwYX47fUaDQK9SR1WjdvTWvxeuwTslCYZXqMv5YKk1Zx+n35JLAvruaWTJUXSRaNkLNplFOXSAffPTTfcaR6HSvvBtrgScQIaDT980Z5073gHyc0BSs61nWnt0RsHxYnwLZSoJ2Yg5rAIxD9Zs2EHqNzgtG04JgBDJSQN4WigUKHftJAOpEp1Zpqlqt84YGMngiZUIht++w9ENVluW9OZynF2b62QNv3yGTBHefVqW4fslkFMY58Jfi6yykq8cphZmzRzgJah9eMIF5ntct0u8FwdacMi+fmW31eFbjVUomRzoSicGy5JHFOLBzkFQ62EURI0tZteH7OunV4aBhJHS1iKXUYaehYvwwIsvzK0VfAMDrRG5YK4nYpYgdwQCHNVwZpqZ5hfZHvl12AalRKRKgnzyKT+X+wW2pA7grpTTNjt2fBiDYm1akdB/qSAHID9DqSQTzP+dEi1MwI+KHSPfIQ99aFLY12qRr4M6Jaze1Fbcp9JQDq2kfYTBfzO8GaJ/Dk8kcdBDMeytVtRy8hVNJWnND8kGhk7SJrebm32nwPcBOUROcawZiC9uhsZP6rwiAmp+7o6Z0iRrmuiYTzXZReQTwsA/eVNB6x90r99L5CNv2afsNFlsSIFkbFZwe+KUZBghTGsDNJ5HNAQsQlyvmzHsdLxByiPYPsW4NQ==
  template:
    metadata:
      name: sealed-secrets
      namespace: argocd
    type: Opaque
