---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgBLSvZYNlY593MCYlCmc6xjPURapnDEztk3u13C8Nr+YgSI4WpqC1OFyicTu85Gqi3SLcnUlpd9d8SHPBceix6+gRg4oW95gWLu6SPGh/2ZYC3hkrzCJWg/pEfRE8sEuDhlhc+WQE0wRtIu8TiQ/lY5eGkjjbTdA8FWaUobPrGCz75uVFgynhlceihRuKvxlS3EGdj0zzJ4VGEDAC2w1REMyymEXs/RmBSND/axPnGudxYaGY4EwAbdgHWdUeoPW5wLKXvbxENp8Yx1YgKBue153ZJok2Rc+on+Q8Jja7njknm3tdSm9fb9PN5J037Rgwon/Jv/VjAElzK7cJ/HMQBg4SNItVEHaHzwUjyZuv5kdB6b2x5G6clmrQq3zmJhEZC2NBzAuxZaD3zcEMoTR6SE6Tlizz3s+FNyiJ6TSRX+h2sFVJGdaGp5uw/iNGkH3wxrp3c48JjwOKH3ZZRrxD9gkI7i3iWzlYhPCdV0OCleEpZibKAI41nEN8u5bNUQRYezX0pneCg9Ms0JXx9iIct9hz+NhNTgCC/F1uzL7lKHOC2zXYfcsYlMNb5RbdbhF7glR+UQ72VEpYdMFTGCzLMyqslyaiUsOZu+y+cHoqWTx7/xhTZSjez5dCxFPioAQsGylYCdgMeNhAXdWkKEEQ8oMIndW9P/fq4Se0wd/dGvYvEsBzUMVgm62BHAGrV2rNA=
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: dev
    type: Opaque
