---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgA2e30UIl/tDp6lj6wtCiSHIKC8k/0TjoM2HOnYds/8OyWzny4AOxS70WUtMSuCuzOY3UVxM0ZTmeDpkN3XZZyTTedrqR3hyAYgui5H8jx6U7j43w3ssKAwU0B1lOdz6gzuz9PLVBrEVlyLiiTwZCDBpfTRCwNogLvlahXW6VkQLbFBdWctUdbPxpE3172whliT9x/0MN+a4zGEVpbLGUFDcdWwr1PGCrHKtfHEH82pWEkSq/FU2d59PuYYoUGzWLeYzb+nj6qGmbNmveQiHvPStgM61YztekzojEctD6dWmZWLYSaRK5/pRjloGGBdzVJmN/qRne3JFF+ypYf5Ww1AF6S9O128KbVzORPWAlVN99ne4jLPIpUce78tRFCE7UMr/NTlhT0kP8W7cWgSqn3gSKIZOHCV9rjssqN+Tl+njKR7I9fUh19L7/OmtDNF6iB7tQAsZwYdRSh7zgY+tqMiHJVSKZD9d39Sh42dg6oSYYzquzF2fQ6XRA4j6U/Sci7YkA6n41kdza34tmaR9axg/UejxReAyRq7h5NccFXQHYvOaSArFP0FKENqDetM8a6o3ysAu4zhdBa691bZ6K5Z42oXpu1davtnbIaFWKbURnh00l51D38ac+5CnDCneGh4xj4xVq3LNnUOib2+NCP9xC3t9UQRtwWr1C0iwvWjET3mtLcXVeP/fUbcNXQTMvm+BuP32wcGOJ/S+NyiRbJUD7Ic+nJPdKyM6Q==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: dev
    type: Opaque
