---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgCpolrVLGgaPVfEEbcu6hmF0R200Tmzunkqr0okD6I9RHj0XTXxD/VLeo8WQkHpoAHLVkH3QuPCg5Q4wDJxoUNB25Qi1KB/iJv3Hcalutnyr//eifJc0FbuGQNlEAvidV7NAU5WDTHdxL0JqvqphrDGRp75wa9C/WZUq1AbGRFbaK4slY0kK5sOBAFgAaNT2Lo9q5Gp9tOosYcubg7U7KeW1Uhf8jXGfUBxAbkpWOmlBAkkSWd+5yecfjYBn1XtDCH0eVi5mTiOIAvTt6ckpLIkkmYyN9htR1WjFiDzSX7cArHLOkKX8zcFgqFMgU+qzD7xlZPeLI+S7nlAK7QoKa544adIp+sgjzmKcB8K4dfmE8w6U4IIDC+VVrFVL5MTE4F1pPNm4w2HubQAQUW/Ua5jY6TTwaT9T59E7tk6N90rn0HiAb9AB0rUiGGr9DGcBePS1mHxKt5Hc8UOhHSEnyCC7KjO5RvFiRkhixQoMqI2ft2G/I9Uw6w1za9DHJTcSsnr8agFN+UqVxelLZmE28vad/AarGRdoYFOnjFBpPYVIwp4dCi1DGIEKAhYTyoZDLecdm0wAp/HBI4yFqnJz1Q7ob2Vh4Su10lPLYRBNA//R7g5ZZhY7M0hzJXIYQUrrbogJZvYJn0e+DVqKqz0YGk/ajwWXD+Cydg0nWZ+nwsaNqMIZ+TN14JFeONyTUeL/Ug=
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: dev
    type: Opaque
