apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_DB
              value: {{ .Values.db.database }}
            # Tomamos la contraseña del Secret desencriptado por Kubeseal
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          ports:
            - containerPort: 5432
