---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: uat
spec:
  encryptedData:
    DB_PASSWORD: AgALMmma/9I9/nXfpPQYYHeF/OLyT0roJxUv31lLDxLpkeOJ+ApBTqZiN8uFhILrrO/ufaAs9bNKjEU7E2vpkObFPCc0U4RfIZ5DaVQ0b3qQqCNXZ+Yse3jZaE6tLv5WW8bwr7RnOPmD3oYn+PWtdlTuGl07eQjyfB2oID1KA2nkJyAtMQq4ZEFE9CVnJ+RgJyhS//ASmJo+6s0Yn+43Z1nhfJpBNNAa7REw/zQ3o8Yj7o99Bbyqev+i870gitf6oImeekGOdqbT8rSKBetTkkdkD/w8ytahMsvM+wV132jQenWZrAbtMjqBofdshcC7KvuPeLdSXUNZKe6jB8jS0AUNox4TRyGE5UeBciTNIT/huUwk0Kd1kHofYHXj+FqNKigsByRof3KV3WqFyUBaCtnHQMO+jFGzkvmTKd/G4x/Fyb7M/uCk++V6meAiw0njPK5ten8CJBxNENbi2uE2MyRlnJ6j1kFIwicTY+SSe2+zhssVzz0maL53ATGCeyHMi3kwE/iapS/6D+iMijIhf6p9VuY7h6qgEusj8zXQp7FyYyiXoXYFsgBAkf3cA+dFiyapLl8VcdGZWHWc7qSt5NQOBmZAOrpJAZpWcU9s1wgLrXAV69wG+JF9lpXDTjfVtcjO5CM4gj/lvawgst6EEstLrnrnGahBtCQ44848sfjzoomisDqgSSLOhf2OzcukOdKBZh/2mQtX
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: uat
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
