---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: uat
spec:
  encryptedData:
    DB_PASSWORD: AgBKKA0BVRx26Zq/es+c5lV+q2IJxN4H4E9ZELOPoN8UBfuQy/tJWIN1NskQFH9gbrXVDlDcJNhWeAekG/O/BZJt56hnbYUQlXbtAGdEcjcflQ0qpdCx9D8Pgzbw/BpV6OwARuxDvNo3fwVbP79lNm7NcYWyjh+YndzDMcwcnwBGJQ7QWCplNX4bI+6mtWgGEGK/jjm71U9k+ve0ZxqQstvipig1meBs9dwYttTUk3bKm/d80/K92k2wVvL3b21Eamz0602Br6qygwT5Vyw2bvA2qLghrJ5AH3Yl6TtA4dtqzfa1AvV5b/wfe7pku+kJ1WZJXo68xNiHqyCFpjPC/4BaGAxrwCiNsZ3R+dTLIduHzuLNdfnIzXURTH3maengkW8MjNZJrrje8e4mUb8WIKbezzotQs7laOrtblRssSRJ8WAFxk5/GSHkztSyIn/K5O3FdDYeg5gApLEGWYL4d0ivcbRagFIt7XdeLc2o/zGLETEVR/2c3Njsv7xRRm94f0RKz5Ha74LYHF8uxq855oMEzoVgJlJcA3rHNafIREd4o403R2B6/p9ZqKL3Av/mEPKm3EmTRuAiNkRhu8x28esM/asdTl89ljNpC/eZC7ZYm+uvOCyak4lZ4KqxnzAaYHAZdpo3V4zWAb7i+Ijz6FiV4cizgL7bZHnU7mggMMOPLlRw1KOQ6AiRcrvsktUfw5IMboHp47jD
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: uat
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
