---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: uat
spec:
  encryptedData:
    DB_PASSWORD: AgCaRyG9Tvz2oClUNnbTjLu8YrwFDvzpeMjZ53AdPD0fK/JduLBhUjYnBw7S5INkrNQGB4o4VL+M/Bh4TfVrYxoC16B7czFXlp1uMdFso2x3xFNLxIE1qW0lq5HoAeQ+i3ZRR7D3bCU2IKJ4tKTontKl8K+B08kPTtKDbaPBz37B3k8x/1IamG3vcZY6FN0cL4hUgRSr+l22wmjhugfO3LiLCxBJ97WamSls25MtxiTkpVHUGdHcbnMqD9suljdh6rQAs5VUPZGUy6Py8p7jkiJXuraua0PC5XxiTBHn8b4z2leyFhJmHsITxHKJQmQal8ycr0DhUhi5MuImZ3BZ4qhYX2QWG6dh8WRjvsTaYRc1KJU9c74BWRIZ9G15NF+Xjbz+/KN08pWXkeYy5FgF9A/x625S/r9psJ0NYoXCA662fYHgA/jPL/RfBqS86I5Uk8PcPiX96EGa2+6RCBOs8XaLh9h20kLHUfH5wGFyvfhWZtOQi5ZXIRlWwos0JWjyS6REmIC3BWxGpoxUZUeMyQXpZe1KjukM/8GN2bMgeKwGRdnjQci4/eNlQGr/mNN6sJWwm2qQ6rLWD+zpcuOOJX9F7OUsGJX4uZy7fZgVSpcTSFbKYq2TSW4kIUz8xqFhmB0m5f/jksKfRot7UrPjwJiHcc8tka+BEws9V6pW+GH4yau4ygKgN7rtsTcT6IxJBiH4KXMTzW+n
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: uat
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
    type: Opaque
