---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: uat
spec:
  encryptedData:
    DB_PASSWORD: AgAbTAagbCQXROUEyeEsXv15JVRKDeIP5w8qs/kGb5YJ3cvLaeE1jVnna6fo+alT/Z6pv5lTgW8cPZXIK2jiJwGxWWmnOTz0aAx9xNjs1t9axh3KTv+NTY3/PlZQatCjpSUOOTgQNkS0FTLvPSfhXH3+PeY8KVXcAqjTV98NZPKbJR6CJHN3XVSjevQGcLWeDsqD1lF1aNsWr8mnNtDODrhJPdDc2TEJWVaCprT9YqKSg9+S9OWLBd2rY/7RWz67h68qNQAVqn0gIWPKnLhxUknwhr4uuTRtdQIqA87Cebu9OAUC0NAvNTDGXP70wye7bUCm7tw3lIbqj7Uu4n3QeVb51Znq7ACnrTkRfMNGcK+7Qepe0vMFzQiOEvuvOg6MY9ERItAcyZUWGifaBdaugh6tWu6ZIThQWNHBfEv0cnAfPG4sHRB47+1TeY67b0N5BLGqDgtVX6M65+6cCUR4pXAl/sCk8bDDELBO78DLftk5RizFERw2pVV7rTEfPEu1YbxvamXEi+y5L78zOxL17vQBgMhy0wYVBuEruX00ZZjUbss5BrtyTOPzb/CExXsIX2W/tkndu+jxYidmJKVGPxJd3rftYhkLkFsdR8MdoQLufrs7sWJLJ4QHJ/709Z/ODKT5l+RFDZkOY49JKZVeNC73+SePU/XoWhxfKQY0D/gbW2UUGyqXjAWdC14P9V/1ryWolPFc6WYJYXTxS3kvoo/hW+iA3s2kNA==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: uat
    type: Opaque
