name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        export IMGTAG=$(git -C ${PWD} rev-parse --short="12" HEAD)
        echo "IMGTAG=$IMGTAG" >> "$GITHUB_OUTPUT"
        cd app
         
        docker build . --file Dockerfile --tag cabunga/argocdtest:$IMGTAG
        docker push cabunga/argocdtest:$IMGTAG
