name: Update Sealed Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to update"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prd

jobs:
  seal-secret:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubeseal
        run: |
          wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.5/kubeseal-linux-amd64.tar.gz
          tar -xvzf kubeseal-linux-amd64.tar.gz
          chmod +x kubeseal
          sudo mv kubeseal /usr/local/bin/

      - name: Define variables
        id: vars
        run: |
          ENV=${{ github.event.inputs.environment }}

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "SECRET_PATH=k8s/$ENV/secrets/sealed-secret.yaml" >> $GITHUB_ENV
          echo "CERT_PATH=certs/$ENV-cert.pem" >> $GITHUB_ENV

      - name: Generate temporary secret yaml
        run: |
          cat <<EOF > secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: db-credentials
            namespace: ${ENV}
          type: Opaque
          stringData:
            DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
          EOF

      - name: Seal secret
        run: |
          kubeseal \
            --cert ${CERT_PATH} \
            -o yaml \
            < secret.yaml \
            > ${SECRET_PATH}

      - name: Validate generated file
        run: |
          cat ${SECRET_PATH}

      - name: Commit changes if needed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add ${SECRET_PATH}

          if git diff --cached --quiet; then
            echo "No changes detected"
          else
            git commit -m "Update sealed secret for ${ENV}"
            git push
          fi
