name: Generate Sealed Secret

on:
  workflow_dispatch:

jobs:
  seal:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubeseal
        run: |
          wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.5/kubeseal-linux-amd64
          chmod +x kubeseal-linux-amd64
          sudo mv kubeseal-linux-amd64 /usr/local/bin/kubeseal

      - name: Create secret yaml
        run: |
          cat <<EOF > secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: app-secret
            namespace: myapp
          type: Opaque
          stringData:
            DB_USER: "${{ secrets.DB_USER }}"
            DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
            DB_HOST: "${{ secrets.DB_HOST }}"
          EOF

      - name: Seal secret
        run: |
          kubeseal \
            --cert certs/dev-cert.pem \
            -o yaml < secret.yaml \
            > clusters/dev-cluster/sealed-secret.yaml

      - name: Commit changes
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "update dev secret"
          git push
