name: Update Sealed Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prd

jobs:
  update-secret:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    permissions:
      contents: write

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubeseal
        run: |
          wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.26.1/kubeseal-0.26.1-linux-amd64.tar.gz
          tar -xvzf kubeseal-0.26.1-linux-amd64.tar.gz
          sudo install -m 755 kubeseal /usr/local/bin/kubeseal
          #wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.5/kubeseal-linux-amd64.tar.gz
          #tar -xvzf kubeseal-linux-amd64.tar.gz
          #chmod +x kubeseal
          #sudo mv kubeseal /usr/local/bin/

      - name: Rebuild certificate from GitHub secret
        run: |
          if [ "${ENVIRONMENT}" = "dev" ]; then
            echo "${{ secrets.SEALED_SECRET_CERT_DEV }}" > dev-cert.pem
            echo "CERT_FILE=dev-cert.pem" >> $GITHUB_ENV

          elif [ "${ENVIRONMENT}" = "uat" ]; then
            echo "${{ secrets.SEALED_SECRET_CERT_UAT }}" > uat-cert.pem
            echo "CERT_FILE=uat-cert.pem" >> $GITHUB_ENV

          elif [ "${ENVIRONMENT}" = "prd" ]; then
            echo "${{ secrets.SEALED_SECRET_CERT_PRD }}" > prd-cert.pem
            echo "CERT_FILE=prd-cert.pem" >> $GITHUB_ENV

          else
            echo "Ambiente no válido"
            exit 1
          fi
      - name: Define paths
        run: |
          echo "SECRET_FILE=app/secret.yml" >> $GITHUB_ENV
          echo "SEALED_FILE=k8s/templates/sealed-secret.yaml" >> $GITHUB_ENV
      - name: Replace placeholders
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}          
        run: |
          envsubst < ${SECRET_FILE} > rendered-secret.yaml
          cat rendered-secret.yaml

      - name: Validate kind Secret
        run: |
          KIND=$(grep "^kind:" rendered-secret.yaml | awk '{print $2}')

          if [ "$KIND" != "Secret" ]; then
            echo "El archivo no es tipo Secret"
            exit 1
          fi
      - name: Generate temporary secret yaml
        if: false
        run: |
          cat <<EOF > secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: db-credentials
            namespace: ${ENVIRONMENT}
          type: Opaque
          stringData:
            DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
          EOF

      - name: Define target file
        run: |
          echo "TARGET_FILE=k8s/templates/sealed-secret.yaml" >> $GITHUB_ENV

      - name: Seal secret
        run: |
          kubeseal \
            --cert ${CERT_FILE} \
            -o yaml \
            < rendered-secret.yaml \
            > ${TARGET_FILE}
      - name: Add managed annotation
        run: |
          yq eval '
            .spec.template.metadata.annotations."sealedsecrets.bitnami.com/managed" = "true"
            ' ${TARGET_FILE} > ${TARGET_FILE}


      - name: Validate output
        run: |
          cat ${TARGET_FILE}

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add ${TARGET_FILE}

          if git diff --cached --quiet; then
            echo "No changes detected"
          else
            git commit -m "Update sealed secret for ${ENVIRONMENT}"
            git push
          fi
